### ISSUE TITLE
Mill's idea generator should include it's api in the project libraries by default

### ISSUE THREAD

**Issue by markehammons** [lihaoyi/mill#523] opened 2018-12-26 20:56 UTC
When editing my build.sc in intellij, I have no checking available because the mill api is all missing from the generated project. By adding the following, intellij's syntax highlighting and autocomplete starts working for build.sc files.

```scala  
override def compileIvyDeps: Target[Loose.Agg[Dep]] = Agg(
    ivy"com.lihaoyi::mill-scalalib:0.3.5"
)
```

Would it be feasible to have this injected into the project dependencies for intellij by default?

**Comment by andres-pipicello-olx** [comment] 2019-05-27 01:04
Could you please include a minimal example? I am not able to reproduce the problem.

**Comment by lefou** [comment] 2019-08-26 19:52
Might be fixed since then? No feedback. Closing.

**Closed by lefou** 2019-08-26 19:52 UTC
