### ISSUE TITLE
Dependency on cats-core crashes console

### ISSUE THREAD

**Issue by ryan-williams** [lihaoyi/mill#368] opened 2018-06-09 18:13 UTC
mill 0.2.2 via `brew`, empty project, `build.sc`:

```scala
import mill._, mill.scalalib._
object test1 extends ScalaModule {
  def scalaVersion = "2.11.12"
}
object test2 extends ScalaModule {
  def scalaVersion = "2.11.12"
  def ivyDeps = Agg(ivy"org.typelevel::cats-core:1.0.1")
}
object test3 extends ScalaModule {
  def scalaVersion = "2.12.6"
  def ivyDeps = Agg(ivy"org.typelevel::cats-core:1.0.1")
}
```

## `mill -i test1.console`

works fine:

```
Compiling (synthetic)/ammonite/predef/interpBridge.sc
Compiling (synthetic)/ammonite/predef/DefaultPredef.sc
Compiling /Users/ryan/c/mill-bug/build.sc
[25/30] test1.compile
Compiling compiler interface...
warning: there was one deprecation warning; re-run with -deprecation for details
warning: there were three feature warnings; re-run with -feature for details
two warnings found
[30/30] test1.console
Welcome to Scala 2.11.12 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_111).
Type in expressions for evaluation. Or try :help.

scala> :q
```

## `mill -i test2.console`

crashes after the opening prompt:

```
[30/30] test2.console
Welcome to Scala 2.11.12 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_111).
Type in expressions for evaluation. Or try :help.

scala>
Failed to initialize compiler: NoSuchMethodError.
This is most often remedied by a full clean and recompile.
Otherwise, your classpath may continue bytecode compiled by
different and incompatible versions of scala.

java.lang.NoSuchMethodError: scala.reflect.internal.Definitions$definitions$.classExistentialType(Lscala/reflect/internal/Types$Type;Lscala/reflect/internal/Symbols$Symbol;)Lscala/reflect/internal/Types$Type;
	at scala.tools.nsc.symtab.classfile.ClassfileParser.processClassType$1(ClassfileParser.scala:681)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.sig2type$1(ClassfileParser.scala:690)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.sig2type$1(ClassfileParser.scala:720)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.scala$tools$nsc$symtab$classfile$ClassfileParser$$sigToType(ClassfileParser.scala:773)
	at scala.tools.nsc.symtab.classfile.ClassfileParser$ConstantPool.getType(ClassfileParser.scala:289)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseMethod(ClassfileParser.scala:568)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.scala$tools$nsc$symtab$classfile$ClassfileParser$$queueLoad$1(ClassfileParser.scala:483)
	at scala.tools.nsc.symtab.classfile.ClassfileParser$$anonfun$parseClass$1.apply$mcV$sp(ClassfileParser.scala:493)
	at scala.tools.nsc.symtab.classfile.ClassfileParser.parseClass(ClassfileParser.scala:498)
…
```

[full output](https://gist.github.com/ryan-williams/911e2c6c954341bcd99b2c6d1eb19d59#file-test2-console-fails)

## `mill -i test3.console`

also crashes after the opening prompt:

```
Compiling /Users/ryan/c/mill-bug/build.sc
[25/30] test3.compile
Compiling compiler interface...
warning: there was one deprecation warning (since 2.11.0)
warning: there were four deprecation warnings (since 2.12.0)
warning: there were 5 deprecation warnings in total; re-run with -deprecation for details
warning: there were three feature warnings; re-run with -feature for details
four warnings found
[30/30] test3.console
Welcome to Scala 2.12.6 (Java HotSpot(TM) 64-Bit Server VM, Java 1.8.0_111).
Type in expressions for evaluation. Or try :help.

scala> java.lang.IncompatibleClassChangeError: Implementing class
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
…
1 targets failed
test3.console ammonite.ops.InteractiveShelloutException
    mill.modules.Jvm$.baseInteractiveSubprocess(Jvm.scala:74)
    mill.modules.Jvm$.interactiveSubprocess(Jvm.scala:34)
    mill.scalalib.ScalaModule.$anonfun$console$1(ScalaModule.scala:152)
    mill.define.ApplyerGenerated.$anonfun$zipMap$1(ApplicativeGenerated.scala:5)
    mill.define.Task$MappedDest.evaluate(Task.scala:348)
```

[Full output](https://gist.github.com/ryan-williams/911e2c6c954341bcd99b2c6d1eb19d59#file-test3-console-fails)

I observe the same thing depending against `cats-core:1.1.0`.

**Comment by lihaoyi** [comment] 2018-06-09 18:31
Looks like the problem is that cats is pulling in incompatible scala-reflect and scala-compiler dependencies and we are not properly filtering them out 

```scala
lihaoyi test$ mill -i show test2.scalaCompilerClasspath
[1/1] show
[
    "qref:fa558888:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-compiler/2.11.12/scala-compiler-2.11.12.jar",
    "qref:1ef351c2:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar",
    "qref:1bbc1f6e:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.12/scala-reflect-2.11.12.jar",
    "qref:16077b3e:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-xml_2.11/1.0.5/scala-xml_2.11-1.0.5.jar",
    "qref:36188735:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-parser-combinators_2.11/1.0.4/scala-parser-combinators_2.11-1.0.4.jar"
]
lihaoyi test$ mill -i show test2.runClasspath
[1/1] show
[6/29] test2.sources
[
    "ref:c984eca8:/Users/lihaoyi/test/test2/resources",
    "ref:c984eca8:/Users/lihaoyi/test/out/test2/compile/dest/classes",
    "qref:1ef351c2:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.11.12/scala-library-2.11.12.jar",
    "qref:9ece9471:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/typelevel/cats-core_2.11/1.0.1/cats-core_2.11-1.0.1.jar",
    "qref:9aea9a64:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-reflect/2.11.8/scala-reflect-2.11.8.jar",
    "qref:0de6f772:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/typelevel/cats-kernel_2.11/1.0.1/cats-kernel_2.11-1.0.1.jar",
    "qref:c41e6d8b:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/typelevel/cats-macros_2.11/1.0.1/cats-macros_2.11-1.0.1.jar",
    "qref:46d257dd:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/org/typelevel/machinist_2.11/0.6.2/machinist_2.11-0.6.2.jar"
]
```

**Comment by lihaoyi** [comment] 2018-06-09 18:50
Should be fixed in master:
```scala
lihaoyi test$ ~/Dropbox/Github/mill/out/dev/launcher/dest/run -i test2.console
Compiling (synthetic)/ammonite/predef/interpBridge.sc
Compiling (synthetic)/ammonite/predef/DefaultPredef.sc
Compiling /Users/lihaoyi/test/build.sc
[25/30] test2.compile
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/Users/lihaoyi/.coursier/cache/v1/https/repo1.maven.org/maven2/com/google/protobuf/protobuf-java/3.3.1/protobuf-java-3.3.1.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
[30/30] test2.console
Welcome to Scala 2.11.12 (Java HotSpot(TM) 64-Bit Server VM, Java 10.0.1).
Type in expressions for evaluation. Or try :help.

scala>  import cats._, cats.data._, cats.implicits._
import cats._
import cats.data._
import cats.implicits._

scala> 1 === 1
res0: Boolean = true

scala> 1 === "foo"
<console>:21: error: type mismatch;
 found   : String("foo")
 required: Int
       1 === "foo"
             ^

scala> (Some(1): Option[Int]) =!= (Some(2): Option[Int])
res2: Boolean = true

scala> :q
lihaoyi test$ ~/Dropbox/Github/mill/out/dev/launcher/dest/run -i test2.repl
[29/29] test2.repl
Loading...
Compiling (synthetic)/ammonite/predef/interpBridge.sc
Compiling (synthetic)/ammonite/predef/replBridge.sc
Compiling (synthetic)/ammonite/predef/DefaultPredef.sc
Welcome to the Ammonite Repl 1.1.2
(Scala 2.11.12 Java 10.0.1)
If you like Ammonite, please support our development at www.patreon.com/lihaoyi
@ import cats._, cats.data._, cats.implicits._
import cats._, cats.data._, cats.implicits._

@  1 === 1
res1: Boolean = true

@  1 === "foo"
cmd2.sc:1: type mismatch;
 found   : String("foo")
 required: Int
val res2 = 1 === "foo"
                 ^
Compilation Failed

@  (Some(1): Option[Int]) =!= (Some(2): Option[Int])
res2: Boolean = true

@ Bye!
lihaoyi test$
```

**Closed** 2018-06-09 18:49 UTC

**Comment by lihaoyi** [comment] 2018-06-09 22:11
@ryan-williams you can use the unstable release `0.2.3-11-e8c1a8` until we get around the tagging the next version
