### ISSUE TITLE
Better Windows Support

### ISSUE THREAD

**Issue by sirinath** [lihaoyi/mill#980] opened 2020-10-21 04:33 UTC
Currently, the background demon does not work properly on Windows. This I believe generates `Failed to connect to server` errors.

**Comment by lihaoyi** [comment] 2020-10-21 05:17
Going to close this as not a proper issue. Feel free to open another one once you have more details etc. w.r.t what the issue is,  and what a fix would look like

**Closed by lihaoyi** 2020-10-21 05:17 UTC

**Comment by sirinath** [comment] 2020-10-21 05:29
After saving `mill.bat` created an empty `build.sc` and ran mill. I get `←[31mSelector cannot be empty←[39m` `Failed to connect to server`.

When I type `mill --help` I get
```
Mill Build Tool
usage: mill [mill-options] [target [target-options]]

  -c, --code           Pass in code to be run immediately in the REPL
  -h, --home           The home directory of the REPL; where it looks for config and caches
  -p, --predef      Failed to connect to server
```

According to this comment on Gitter:

> I assume this is on Windows. I also develop `mill`-based projects on Windows sometimes. Use the `-i` command-line argument -- the background daemon stuff normally used by `mill` doesn't seem to work on Windows, at least not out of the box. `-i` turns that stuff off, and seems to get `mill` working on Windows.

So is it possible to bring windows in parity with other platforms by fixing this issue?

**Comment by lefou** [comment] 2020-10-21 08:43
> So is it possible to bring windows in parity with other platforms by fixing this issue?

Yes

**Comment by sirinath** [comment] 2020-10-21 10:22
Can this be fixed so Mill is in parity with other systems on Windows also?

> what the issue is, and what a fix would look like
- Issue: getting `Failed to connect to server` errors since demons are not working on Windows. Disabling demons make Mill handicapped (without the full feature set) on Windows.
- Fix required: get demons working on Windows so Mil on Windows is in parity with other systems

**Comment by lefou** [comment] 2020-11-28 18:34
We gladly accept contributions, e.g. in form of helpful hints how to fix it (on Gitter), questions to better understand the issue (on Gitter) or pull requests (here).
