### ISSUE TITLE
Repl command shouldn't eval ~/.ammonite/predef.sc 

### ISSUE THREAD

**Issue by narma** [lihaoyi/mill#301] opened 2018-04-17 13:30 UTC
My `~/.ammonite/predef.sc` is project independent file which contains imports of libraries for common daily use and it contain conflict libraries and/or versions with project libraries/versions use.

Probably this behaviour should be configurable at least.

UPD: I should clarify that ammonite's `predef.sc` is used when I execute `mill -i module.repl`. In my scenario this is not preferred behavior. I don't want global ammonite's predef in my project's REPL.

**Comment by rockjam** [comment] 2018-04-19 21:47
Should be fine in 0.2.0. @narma may we close it?

**Comment by narma** [comment] 2018-04-25 11:44
@Baccata I should clarify that ammonite's `predef.sc` is used when I execute `mill -i module.repl`. In my scenario this is not preferred behavior. I don't want global ammonite's predef in my project's REPL.

**Comment by Baccata** [comment] 2018-04-25 11:58
I'm no maintainer, but I no the codebase a bit and maybe I could have helped. As @rockjam (who is a maintainer) says, this should be fixed in version >= 0.2.0. Which version are you running ?

**Comment by rockjam** [comment] 2018-04-25 12:06
@Baccata we were actually talking about two different things.
First I thought that the issue is that `predef` of ammonite is used when you run `mill` itself, but it turns out that it happens only in `repl` command. This may for instance lead to a situation when there are conflicting versions of libraries in the classpath - one from your project's classpath and another from ammonite's `predef`

**Comment by lihaoyi** [comment] 2018-04-25 15:11
I think I'm going to call this a wontfix; Mill's Ammonite using `~/.ammonite/predef.sc` behaves the same as using Ammonite from SBT. If you wish to override the default, you can do so by `override`ing `def repl` and passing in the `--predef foo.sc` flag to point your predef at whatever file you wish

**Closed by lihaoyi** 2018-04-25 15:11 UTC
