### ISSUE TITLE
mill compile return the wrong return code.

### ISSUE THREAD

**Issue by seieewkx** [lihaoyi/mill#420] opened 2018-08-30 04:56 UTC
We use `mill` to compile java/scala code in our project, because it's the fastest building tool.

Our project depends on the correct return code of the compiler, we find that in some special situation, `mill` compile return the wrong code. I have created a minimal demo for this error.

https://github.com/seieewkx/mill_compile_bug_demo/tree/master

Thank you very much! 
Looking forward to your reply!

**Comment by aosagie** [comment] 2018-09-02 14:57
I couldn't reproduce. I get "1" as expected.
![screenshot from 2018-09-02 10-49-39](https://user-images.githubusercontent.com/1888108/44957294-b89a8400-ae9e-11e8-8831-155dae427661.png)

What's your java version, shell and OS?

**Comment by seieewkx** [comment] 2018-09-03 02:39
Thanks for reply.

**OS**: ubuntu16.04
**Shell**: zsh (in the picture blow), I can reproduce this on bash too.
**java**: 
```
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-0ubuntu0.16.04.1-b11)
OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
```
**mill**:  `0.2.6`

![image](https://user-images.githubusercontent.com/5382732/44964846-201b0700-af65-11e8-933a-c5bf22fb4550.png)

**Comment by seieewkx** [comment] 2018-09-03 02:43
I don't know why there is an extra `Connection reset by peer` error at the end of `mill foo.compile` error log. I rerun the compilation, the error exists, but the `Connection reset by peer` disappears. 
![image](https://user-images.githubusercontent.com/5382732/44964982-e5fe3500-af65-11e8-8a37-5fe6e00cdc21.png)

**Comment by lefou** [comment] 2018-10-25 18:37
Is this still an issue with latest mill release (0.3.2)?

**Comment by lefou** [comment] 2019-02-18 21:30
Closing this. Please re-open, if this issue is still present with current verisons of mill.

**Closed by lefou** 2019-02-18 21:31 UTC
