### ISSUE TITLE
If project contains lib "org.java-websocket:Java-WebSocket:1.3.7", it can't be generated when generating IDEA files

### ISSUE THREAD

**Issue by freewind** [lihaoyi/mill#153] opened 2018-02-23 15:36 UTC
build.sc:

```
import mill._
import mill.scalalib._

object hello extends ScalaModule {
  override def scalaVersion = "2.12.4"
  override def ivyDeps = Agg(
    ivy"org.java-websocket:Java-WebSocket:1.3.7",
    ivy"org.scala-lang:scala-reflect:${scalaVersion()}"
  )
}
```

There is `ivy"org.java-websocket:Java-WebSocket:1.3.7"` in build.sc, but when generate IDEA files by `mill mill.scalalib.GenIdeaModule/idea`, the generated library xml file doesn't contain it, see `.idea/libraries/` files (they are added to git)

A complete mini project to represent the issue: <https://github.com/scala-demos/mill-java-websocket-generating-issue-demo>

**Comment by freewind** [comment] 2018-02-23 15:41
It's quite strange that the Java-WebSocket files:

```
Java_WebSocket_1_3_7_jar.xml
Java_WebSocket_1_3_7_sources_jar.xml
```

were not generated in the first 4 times run, but were generated in the 5th time.

**Comment by ajrnz** [comment] 2018-02-23 16:09
It looks like you are using mill 0.1.0? There are significant changes on the current build and it seems to work there.

**Comment by freewind** [comment] 2018-02-24 01:15
@ajrnz Sorry, the README is outdated about the mill version. I built the mill from the latest code, and it happens with it. I will update the README of the demo

**Comment by freewind** [comment] 2018-02-25 05:54
This is seem to be a very randomly issue. Today I add two dependences to my project:

```
    ivy"ch.qos.logback:logback-classic:1.2.3",
    ivy"org.slf4j:slf4j-api:1.7.25",
```
The `org.slf4j:slf4j-api:1.7.25` is generated correctly, but `ch.qos.logback:logback-classic:1.2.3` is not.  I re-run `mill mill.scalalib.GenIdeaModule/idea` several times and finally it comes out.

I'm not sure if it has something with network, since the network to foreign country is not stable and often blocked randomly.

**Comment by ajrnz** [comment] 2018-02-25 12:18
I don't think this is a problem will mill. I've run `GenIdea` on your project with the latest version and it works for me. The resolution part of mill is handled by coursier. Maybe you could try renaming your `~/.ivy2` and `~/.coursier` directories and see if there is a problem with your cache? Also it could be a problem with an unstable connection (as you say).

**Comment by lihaoyi** [comment] 2018-02-27 03:51
I've had problems with the coursier resolution not being deterministic in the face of network problems. I'm sure it's our fault in how we're using coursier

**Comment by freewind** [comment] 2018-02-28 10:46
It seems I have to run `mill foo.compile` before `mill mill.scalalib.GenIdeaModule/idea` to make it generate the missing library files

**Comment by rockjam** [comment] 2018-03-31 19:57
@freewind I wasn't able to reproduce this issue. Can you confirm that it's still there on the latest release version of mill? (0.1.7)

**Comment by rockjam** [comment] 2018-04-06 20:27
Closing this for now, will reopen if it still reproduces

**Closed by rockjam** 2018-04-06 20:27 UTC
