### ISSUE TITLE
Task jar: same input, different output

### ISSUE THREAD

**Issue by m-a-t** [lihaoyi/mill#551] opened 2019-02-17 13:15 UTC
Observed behaviour: Even without input changing (inputsHash stays the same), the result of the jar task is different.

I guess this happens because createJar uses modification time from the file system. I propose the following solution: Make createJar not depend on mtime anymore, rather set a constant value.

**Comment by lefou** [comment] 2019-02-17 16:51
Do you have a minimal reproducing example?

**Comment by m-a-t** [comment] 2019-02-17 22:46
It's very simple to reproduce, steps:

1. Download http://www.lihaoyi.com/mill/example-1.zip
2. Unzip, cd into the project dir
3. Run "mill foo.jar"
4. Rename directory out/foo/jar to out/foo/jar-reference
5. Run again "mill foo.jar"
6. Compare the new out/foo/jar with out/foo/jar-reference: Despite the inputs didn't change, the output most probably changed

**Comment by lefou** [comment] 2019-02-17 23:07
What you are after at is called "reproducible builds". 

For the record: there is a Maven Plugin (https://github.com/zlika/reproducible-build-maven-plugin) and also a sbt plugin (https://github.com/raboof/sbt-reproducible-builds) using the Maven plugins library under the hood. But nobody wrote one for mill.

There is also the mill-osgi plugin (https://github.com/lefou/mill-osgi), which produces OSGi bundles. It has an option (which is enabled by default) to create reproducible JARs. OSGi bundles are just normal JARs with some extra metadata in the manifest. I'm the author of that plugin.

**Comment by lihaoyi** [comment] 2019-02-18 03:49
I think bit-for-bit reproducible builds is out of scope for Mill as of now. Not because reproducible builds are a bad thing, but simply because they aren't necessary for the bulk of use cases. Feel free to send PRs to make things more reproducible where-ever you'd like, but I won't commit to working on that or not accidentally breaking reproducibility guarantees

**Closed by lihaoyi** 2019-02-18 03:49 UTC
