### ISSUE TITLE
Specify resolvers for `mill mill.scalalib.GenIdea/idea`

### ISSUE THREAD

**Issue by nh13** [lihaoyi/mill#679] opened 2019-08-23 16:32 UTC
I tried asking [gitter](https://gitter.im/lihaoyi/mill?at=5d601176a498b6723782c5a4), but looking briefly at the code, I could not copy-paste `mill.scalalib.GenIdea` into my build file to override the resolvers, so perhaps this needs to be an "enhancement".

> I want to run mill mill.scalalib.GenIdea/idea when my project depends on snapshots. I get a 
> failure for resolution failures. I have added additional resolvers for my build, but how do I do the same for the task to generate idea files?
> Here's a gist with more (log) information: https://gist.github.com/nh13/2624f965fcf359dd672b81b6a8aedd9c
> Thank-you for any help folks could offer in advance.

**Comment by lefou** [comment] 2019-09-05 08:13
Can you post your `build.sc` to reproduce the issue. GenIdea should use the resolvers defined in your modules to fetch libraries required by your modules.

**Comment by lefou** [comment] 2019-12-09 13:34
Closing due to missing feedback.

**Closed by lefou** 2019-12-09 13:34 UTC
