### ISSUE TITLE
Errors in log mill 0.1.3

### ISSUE THREAD

**Issue by rockjam** [lihaoyi/mill#167] opened 2018-02-26 09:07 UTC
This error occurs on mill 0.1.3 every time I run command from shell
```
➜  mill git:(master) ✗ mill dev.assembly
[25/271] moduledefs.compile 
[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
        at java.lang.Integer.parseInt(Integer.java:580)
        at java.lang.Integer.valueOf(Integer.java:766)
        at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
        at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
        at jline.UnixTerminal.<init>(UnixTerminal.java:65)
        at jline.UnixTerminal.<init>(UnixTerminal.java:50)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at java.lang.Class.newInstance(Class.java:442)
        at jline.TerminalFactory.getFlavor(TerminalFactory.java:211)
        at jline.TerminalFactory.create(TerminalFactory.java:102)
        at jline.TerminalFactory.get(TerminalFactory.java:186)
        at jline.TerminalFactory.get(TerminalFactory.java:192)
        at sbt.internal.util.ConsoleAppender$.ansiSupported(ConsoleAppender.scala:245)
        at sbt.internal.util.ConsoleAppender$.<init>(ConsoleAppender.scala:107)
        at sbt.internal.util.ConsoleAppender$.<clinit>(ConsoleAppender.scala)
        at sbt.internal.util.MainAppender$.defaultScreen(MainLogging.scala:61)
        at mill.scalaworker.ScalaWorker.compileScala(ScalaWorker.scala:169)
        at mill.scalalib.ScalaModule.$anonfun$compile$2(ScalaModule.scala:140)
        at mill.define.ApplyerGenerated.$anonfun$zipMap$9(ApplicativeGenerated.scala:21)
        at mill.define.Task$MappedDest.evaluate(Task.scala:358)
        at mill.eval.Evaluator.$anonfun$evaluateGroup$15(Evaluator.scala:303)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at scala.Console$.withErr(Console.scala:192)
        at mill.eval.Evaluator.$anonfun$evaluateGroup$14(Evaluator.scala:303)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at scala.Console$.withOut(Console.scala:163)
        at mill.eval.Evaluator.$anonfun$evaluateGroup$13(Evaluator.scala:302)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
        at scala.Console$.withIn(Console.scala:226)
        at mill.eval.Evaluator.$anonfun$evaluateGroup$9(Evaluator.scala:301)
        at mill.eval.Evaluator.$anonfun$evaluateGroup$9$adapted(Evaluator.scala:259)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at scala.collection.IterableLike.foreach(IterableLike.scala:71)
        at scala.collection.IterableLike.foreach$(IterableLike.scala:70)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at mill.eval.Evaluator.evaluateGroup(Evaluator.scala:259)
        at mill.eval.Evaluator.evaluateGroupCached(Evaluator.scala:186)
        at mill.eval.Evaluator.$anonfun$evaluate$2(Evaluator.scala:89)
        at mill.eval.Evaluator.$anonfun$evaluate$2$adapted(Evaluator.scala:82)
        at scala.collection.Iterator.foreach(Iterator.scala:929)
        at scala.collection.Iterator.foreach$(Iterator.scala:929)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1417)
        at mill.eval.Evaluator.evaluate(Evaluator.scala:82)
        at mill.main.RunScript$.evaluate(RunScript.scala:195)
        at mill.main.RunScript$.$anonfun$evaluateTasks$1(RunScript.scala:181)
        at scala.util.Either.map(Either.scala:350)
        at mill.main.RunScript$.evaluateTasks(RunScript.scala:180)
        at mill.main.RunScript$.$anonfun$runScript$3(RunScript.scala:59)
        at ammonite.util.Res$Success.flatMap(Res.scala:61)
        at mill.main.RunScript$.runScript(RunScript.scala:58)
        at mill.main.MainRunner.$anonfun$runScript$1(MainRunner.scala:76)
        at mill.main.MainRunner.watchLoop2(MainRunner.scala:48)
        at mill.main.MainRunner.runScript(MainRunner.scala:63)
        at mill.Main$.main0(Main.scala:168)
        at mill.ServerMain$.main0(Main.scala:77)
        at mill.clientserver.Server.$anonfun$handleRun$1(Server.scala:81)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by DavidGregory084** [comment] 2018-02-26 10:02
I think this is #139 again

**Comment by lihaoyi** [comment] 2018-02-26 18:16
Yeah probably a dupe of #139

**Closed** 2018-02-26 18:18 UTC
Labels: bug
